version: "3"

services:

  # backend
  backend:
    # コンテナ名
    container_name: node-dev
    # build
    image: node:16
    # コンテナの中に入る
    tty: true
    # 他のコンテナ起動後に起動するように制御
    depends_on:
      - db
    # ボリューム
    volumes:
      - ".:/app"
    # WORKDIR
    working_dir: /app
    # 環境変数
    environment:
      TZ: "Asia/Tokyo"
      DATABASE_URL: "mysql://root:password@db:3306/sample1"
    # ポート開放
    ports:
      - 3000:3000
    restart: always
    # 起動コマンド
    command: >
      npm start

  # DBサーバ
  db:
    # コンテナ名
    container_name: db
    # build
    image: mysql
    # 環境設定
    environment:
      TZ: Asia/Tokyo
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: sample1
      MYSQL_USER: app
      MYSQL_PASSWORD: password
    # コンテナの中に入る
    tty: true
    # ボリューム
    volumes:
      - mysql_data:/var/lib/mysql
    # ポート開放
    ports:
      - 3306:3306

# 名前付きボリュームをdockerホストの管理下で作成
volumes:
  #
  mysql_data: {}
